apiVersion : apps/v1
kind: Deployment
metadata:
  name: basilmyonlinestore 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basilmyonlinestore
  template:
    metadata:
      labels:
        app: basilmyonlinestore 
    spec:
      containers:
        - name: basilmyonlinestore 
          image: coitlearning/myonlinestore
          ports:
          - containerPort: 80
